title: "Katie Bucks the Invisible Fucks!"
description: "Sum bullsheet!"
baseurl: "/katiebucks.xyz"
url: "https://katiebucks.github.io"
permalink: /:categories/:title/
markdown: kramdown
theme: minima
timezone: "UTC"
incremental: false

sass:
  sass_dir: "_sass"
  style: compressed

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md
  - .git
  - .github


# Pagination
paginate: 10
paginate_path: "/page:num/"

collections:
  pages:
    output: true
    permalink: /:name/
  posts:
    output: true
    permalink: /:year/:month/:day/:title/
  categories:
    output: true

# Navbar Links
nav_links:
  - title: Home
    url: "/"
  - title: About
    url: "/about/"
  - title: Privacy Guide
    url: "/privacy-guide/"
  - title: PGP
    url: "/pgp/"

assets:
  css: "/assets/css/main.css"
  images: "/assets/images/"

# Default Layouts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

# Optional relative links config
relative_links:
  enabled: true
  collections: true

# Remember: Jekyll won't auto-generate CSP from this block
csp:
  default-src: "'self'"
  img-src: "'self' data:"
  style-src: "'self'"
  font-src: "'self'"
  script-src: "'self'"