title: "KatieBucks.xyz"
description: "Privacy‑first, zero‑tracking hub"
baseurl: ""            # root‑relative deployment
url: "https://katiebucks.xyz"

permalink: /:categories/:title/
markdown: kramdown
theme: minima
timezone: "America/Chicago"
incremental: true

sass:
  sass_dir: "_sass"
  style: compressed

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

exclude:
  - README.md
  - Gemfile*
  - node_modules
  - vendor
  - .git*

# Pagination
paginate: 10
paginate_path: "/page:num/"

# Fixed five‑link navbar
nav_links:
  - title: Home
    url: "/"
  - title: Privacy Guide
    url: "/privacy-guide/"
  - title: Contact
    url: "/contact/"
  - title: Mirrors
    url: "/mirrors/"
  - title: PGP
    url: "/pgp/"

assets:
  css: "/assets/css"
  images: "/assets/images"

# Optional CSP helper reference (enforced via <meta> tag)
csp:
  default-src: "'self'"
  img-src:     "'self' data:"
  style-src:   "'self'"
  font-src:    "'self'"
  script-src:  "'self'"