# _config.yml
title: "Katie Bucks the Invisible FUCKS!"
description: "Personal VLOG/BLOG by Katie Bucks — privacy-first, JS-free."
url: "https://katiebucks.xyz"   # change when deploying
baseurl: ""                     # leave empty unless site lives in a sub-folder
markdown: kramdown
highlighter: rouge

# Pagination
paginate: 5
paginate_path: "/page:num/"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-paginate

# Defaults for posts
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post
      author: "Katie Bucks"

# Permalinks
permalink: /:categories/:year/:month/:day/:title/